version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn resume.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/web

    ports:
      - 8000:8000