name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SSH into VPS and deploy
        uses: appleboy/scp-action@master
        env:
          host: 45.144.31.135
          username: dro
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source: "."
          target: "/usr/resume_site/"

      - name: Build
        uses: appleboy/ssh-action@master
        with:
          host: 45.144.31.135
          username: dro
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd usr/resume_site/ && git pull && docker-compose up -d