name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        with:
          host: 45.144.31.135
          username: dro
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/home/dro/resume_site"

      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@master
        with:
          host: 45.144.31.135
          username: dro
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
              pwd
              ls
              docker-compose -f /home/dro/resume_site/resume/\
              docker-compose.yml up -d